# NOTE: See https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.

keys:
  - &alghoul age1u5d2pvyxd8usuqq9xe97fl78kxkagzt6uykdmdmqc38q9yaa5ghst2k70r
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *alghoul
  - path_regex: secrets/hydra/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *alghoul

